CREATE TABLE test1(ID INT, NAME VARCHAR(30));
CREATE TABLE test2(ID INT, NAME VARCHAR(30));

INSERT INTO test1 VALUES(1, 'fdsaf23r23');
INSERT INTO test1 VALUES(2, 'b');
INSERT INTO test1 VALUES(3, 'c');
