# 当使用database作为注册中心时使用该配置，同时需要在“application.yml”配置文件的“spring.profiles.include”项中增加“registry_database”，即“spring.profiles.include: xxx,registry_database”
disjob.registry.database:
  namespace: mysql_namespace
  session-timeout-ms: 30000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/disjob?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&connectTimeout=2000&socketTimeout=5000&serverTimezone=Asia/Shanghai&failOverReadOnly=false
    username: disjob
    password: disjob$123456
    minimum-idle: 2
    maximum-pool-size: 20
    connection-timeout: 2000
    pool-name: database_registry
