logging.config: classpath:log4j2.xml

# actuator monitor configuration
management:
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
    enabled-by-default: true
  info:
    env:
      enabled: true

# springdoc “swagger-ui” and “api-docs” endpoint custom path, StandaloneLayout/BaseLayout
springdoc:
  swagger-ui:
    path: /apidocs.html
    layout: StandaloneLayout
  api-docs:
    path: /apidocs

# tomcat server configuration
server.tomcat:
  threads:
    max: 500
    min-spare: 20
  accept-count: 200
  max-connections: 20000
  mbeanregistry.enabled: true

# Disjob configuration
disjob:
  http:
    connect-timeout: 3000
    read-timeout: 10000
  retry:
    max-count: 3
    backoff-period: 3000
