# database configuration：前面的`disjob.datasource`为固定前缀，后面的`disjob`为数据源名称
disjob.datasource:
  disjob:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/disjob?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&connectTimeout=2000&socketTimeout=5000&serverTimezone=Asia/Shanghai&failOverReadOnly=false
    username: disjob
    password: disjob$123456
    minimum-idle: 2
    maximum-pool-size: 20
    connection-timeout: 2000
    #connection-test-query: SELECT 1    # jdbc4不建议配置connectionTestQuery
