# 当使用etcd作为注册中心时使用该配置，同时需要在“application.yml”配置文件的“spring.profiles.include”项中增加“registry-etcd”，即“spring.profiles.include: xxx,registry-etcd”
disjob.registry.etcd:
  namespace: disjob_registry
  endpoints: localhost:2379
  user:
  password:
