# Disjob supervisor configuration
disjob.supervisor:
  scan-triggering-job-period-ms: 4500
  scan-waiting-instance-period-ms: 15000
  scan-running-instance-period-ms: 30000
  process-job-maximum-pool-size: 6
