# 当使用zookeeper作为注册中心时使用该配置，同时需要在“application.yml”配置文件的“spring.profiles.include”项中增加“registry-zookeeper”，即“spring.profiles.include: xxx,registry-zookeeper”
disjob.registry.zookeeper:
  namespace: disjob_registry
  connect-string: localhost:2181
  username:
  password:
